<!--
  ExportDryRun.svelte — Virtual file tree preview with content viewer
  Ported from: src/features/export/ui/ExportDryRun.tsx (80 lines)

  Architecture:
    Two-panel layout for previewing the synthesized archive structure before
    final export. Left panel shows the file tree (capped at 500 entries for
    perf). Right panel shows a text preview of the selected file or a
    placeholder for binary assets.

    This is a "pure display" molecule — no side effects, no service calls.
    All data comes from the parent ExportDialog via props.

  FSD Layer: features/export/ui/molecules
  Rule 5.D: Receives cx + fieldMode via props (never resolves theme internally)
  Rule: Molecules < 200 lines (this is ~80 lines of logic, well under limit)
-->

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import type { VirtualFile } from '../../model/exportService';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import { cn } from '@/src/shared/lib/cn';

  interface Props {
    /** Array of virtual files generated by exportService.prepareExport() */
    files: VirtualFile[];
    /** Contextual class names resolved by parent template (Rule 5.D) */
    cx?: Partial<ContextualClassNames>;
    /** Whether field mode (high-contrast black/yellow) is active */
    fieldMode?: boolean;
  }

  let { files, cx = {}, fieldMode = false }: Props = $props();

  /**
   * Currently selected file in the tree.
   * Initialized to the first file in the list (if any).
   * Updated on click in the file tree panel.
   */
  let selectedFile: VirtualFile | null = $state(null);

  // Initialize selectedFile when files prop first arrives or changes
  $effect(() => {
    if (files.length > 0) {
      selectedFile = files[0];
    }
  });

  /**
   * Text preview content of the selected file.
   * - For string content: truncated at 50,000 chars with "[Preview Truncated]" suffix
   * - For Blob content: null (shows binary asset placeholder instead)
   * - For no selection: null (shows empty state)
   */
  let filePreview: string | null = $derived.by(() => {
    if (!selectedFile) return null;
    if (selectedFile.content instanceof Blob) return null;
    if (typeof selectedFile.content === 'string') {
      return selectedFile.content.length > 50_000
        ? `${selectedFile.content.slice(0, 50_000)}\n... [Preview Truncated]`
        : selectedFile.content;
    }
    return null;
  });

  /**
   * Icon name based on file type.
   * Maps VirtualFile.type to Material Icons name for the tree list.
   */
  function fileIcon(type: VirtualFile['type']): string {
    switch (type) {
      case 'json': return 'description';
      case 'html': return 'html';
      case 'asset': return 'image';
      case 'info': return 'description';
      default: return 'insert_drive_file';
    }
  }
</script>

<div class={cn('flex h-[500px] border overflow-hidden shadow-inner', fieldMode ? 'bg-nb-black border-nb-yellow' : 'bg-nb-white')}>
  <!-- File Tree (left panel) -->
  <div class={cn('w-1/3 border-r flex flex-col', fieldMode ? 'bg-nb-black border-nb-yellow' : 'bg-nb-white')}>
    <div class={cn('p-3 border-b flex items-center justify-between', fieldMode ? 'bg-nb-yellow/10 border-nb-yellow' : 'bg-nb-cream')}>
      <span class={cn('text-[10px] font-black uppercase tracking-widest', fieldMode ? 'text-nb-yellow/50' : 'text-nb-black/50')}>
        Bundle Structure
      </span>
      <span class="text-[10px] font-bold text-iiif-blue bg-nb-blue/10 px-1.5 rounded">
        {files.length} Files
      </span>
    </div>
    <div class="flex-1 overflow-y-auto p-2 custom-scrollbar">
      {#each files.slice(0, 500) as f (f.path)}
        <button
          type="button"
          class={cn(
            'flex items-center gap-2 p-2 cursor-pointer text-xs transition-nb w-full text-left border-0 bg-transparent',
            selectedFile?.path === f.path
              ? 'bg-iiif-blue text-white shadow-brutal-sm'
              : fieldMode
                ? 'hover:bg-nb-yellow/10 text-nb-yellow/60'
                : 'hover:bg-nb-cream text-nb-black/60'
          )}
          aria-label={f.path}
          onclick={() => { selectedFile = f; }}
        >
          <Icon
            name={fileIcon(f.type)}
            class={selectedFile?.path === f.path ? 'text-white' : fieldMode ? 'text-nb-yellow/40' : 'text-nb-black/40'}
          />
          <span class="truncate font-mono">{f.path}</span>
        </button>
      {/each}
      {#if files.length > 500}
        <div class={cn('p-4 text-center text-xs italic', fieldMode ? 'text-nb-yellow/40' : 'text-nb-black/40')}>
          ... and {files.length - 500} more files
        </div>
      {/if}
    </div>
  </div>

  <!-- Preview Area (right panel) -->
  <div class="flex-1 bg-nb-black flex flex-col overflow-hidden">
    <div class="p-3 bg-nb-black border-b border-white/10 flex justify-between items-center">
      <div class="flex items-center gap-2">
        <Icon name="visibility" class="text-nb-blue text-sm" />
        <span class="text-xs font-bold text-nb-black/30 font-mono truncate max-w-[200px]">
          {selectedFile?.path}
        </span>
      </div>
      {#if selectedFile?.type === 'json'}
        <div class="text-[9px] font-black bg-nb-green/20 text-nb-green px-1.5 py-0.5 border border-nb-green/30 uppercase">
          Synthesized
        </div>
      {/if}
    </div>
    <div class="flex-1 overflow-auto p-4 custom-scrollbar">
      {#if selectedFile}
        {#if selectedFile.content instanceof Blob}
          <div class="h-full flex flex-col items-center justify-center text-nb-black/50 gap-4">
            <Icon name="image" class="text-6xl opacity-20" />
            <div class="text-center">
              <p class="text-xs font-bold uppercase text-nb-black/40">Binary Asset</p>
              <p class="text-[10px] opacity-60">File contents hidden in preview</p>
            </div>
          </div>
        {:else}
          <pre class="text-[11px] font-mono text-nb-blue/40 leading-relaxed whitespace-pre-wrap break-all">{filePreview}</pre>
        {/if}
      {:else}
        <div class="h-full flex items-center justify-center text-nb-black/60 italic text-sm">
          Select a file to preview output
        </div>
      {/if}
    </div>
  </div>
</div>
